version: '3.8'
services:
  telegram_bot:
    build:
      context: apps/telegram_bot/.
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file: .env


  chain_listener:
    build:
      context: apps/chain_listener/.
      dockerfile: Dockerfile
    env_file: .env


  registry:
    build:
      context: apps/registry/.
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    env_file: .env
    volumes:
      - ./apps/registry/data:/app

  webapp:
    build: 
      context: apps/webapp/.
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file: .env


